//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoryEntities : DbContext
    {
        public LaboratoryEntities()
            : base("name=LaboratoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Analizator> Analizator { get; set; }
        public virtual DbSet<Byxgalter> Byxgalter { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<Laborant> Laborant { get; set; }
        public virtual DbSet<LaborantYslugi> LaborantYslugi { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<PacientInsuranse> PacientInsuranse { get; set; }
        public virtual DbSet<ServiceRendered> ServiceRendered { get; set; }
        public virtual DbSet<Stcet> Stcet { get; set; }
        public virtual DbSet<YslugiLaboratorii> YslugiLaboratorii { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
        public virtual DbSet<ZakazYsluga> ZakazYsluga { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
    }
}
