//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientInsuranse
    {
        public int Id { get; set; }
        public Nullable<int> CodPacient { get; set; }
        public Nullable<int> CodInsuranceCompany { get; set; }
        public string TypePolic { get; set; }
        public Nullable<int> NumberPolic { get; set; }
    
        public virtual InsuranceCompany s5_InsuranceCompany { get; set; }
        public virtual Pacient s5_Pacient { get; set; }
    }
}
