//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.s5_PacientInsuranse = new HashSet<PacientInsuranse>();
            this.s5_Zakaz = new HashSet<Zakaz>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sername { get; set; }
        public string Patronomic { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> DateOfBirthday { get; set; }
        public Nullable<int> SeriaPassport { get; set; }
        public Nullable<int> NumberPasport { get; set; }
        public string Phone { get; set; }
        public string Pochta { get; set; }
        public string Fio
        {
            get
            {
                return Sername + " " + Name + " " + Patronomic;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacientInsuranse> s5_PacientInsuranse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> s5_Zakaz { get; set; }
    }
}
