//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRendered
    {
        public int Id { get; set; }
        public Nullable<int> CodYslugi { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CodLaborant { get; set; }
        public Nullable<int> CodAnalizator { get; set; }
    
        public virtual Analizator s5_Analizator { get; set; }
        public virtual Laborant s5_Laborant { get; set; }
    }
}
