//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stcet
    {
        public int Id { get; set; }
        public Nullable<int> Cod_Zakaz { get; set; }
        public Nullable<int> CodByxgalter { get; set; }
    
        public virtual Byxgalter s5_Byxgalter { get; set; }
        public virtual Zakaz s5_Zakaz { get; set; }
    }
}
