//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YslugiLaboratorii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YslugiLaboratorii()
        {
            this.s5_LaborantYslugi = new HashSet<LaborantYslugi>();
            this.s5_ZakazYsluga = new HashSet<ZakazYsluga>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Prise { get; set; }
        public Nullable<int> CodYslugi { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> AverageDeviation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaborantYslugi> s5_LaborantYslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazYsluga> s5_ZakazYsluga { get; set; }
    }
}
