//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazYsluga
    {
        public int Id { get; set; }
        public Nullable<int> CodZakaz { get; set; }
        public Nullable<int> CodYslugi { get; set; }
        public string StatysYslugi { get; set; }
        public Nullable<int> CodLaborant { get; set; }
    
        public virtual Laborant s5_Laborant { get; set; }
        public virtual YslugiLaboratorii s5_YslugiLaboratorii { get; set; }
        public virtual Zakaz s5_Zakaz { get; set; }
    }
}
